[build]
  command = "hugo --gc --minify --environment production --config config.toml"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.7"
  HUGO_ENV = "production"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "no-store"
