[build]
  command = "hugo --gc --minify --environment production --config config.toml"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.7"
  HUGO_ENV = "production"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "no-store"
    X-Robots-Tag = "all"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "no-store"
    X-Robots-Tag = "all"
    Access-Control-Allow-Origin = "*"
